---
title: "Intro to Git"
output: html_document
date: "2024-01-22"
---

```{r}
library(palmerpenguins)
library(tidyverse)
theme_set(theme_minimal())
penguins
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_freqpoly()
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(colour = "black", fill = "white", bins = 15) +
  facet_wrap(~ species)
```

```{r}
ggplot(data = penguins, aes(x = species)) +
  geom_bar(stat = "count") ## don't need stat = "count" because it's the default.
```

```{r}
penguins_sum <- penguins |> group_by(species) |>
  summarise(n_count = n())
ggplot(data = penguins_sum, aes(x = species, y = n_count)) + 
  geom_bar(stat = "identity")
## equivalent to
ggplot(data = penguins_sum, aes(x = species, y = n_count)) +
  geom_col()
```

```{r}
ggplot(data = penguins, aes(x = species, fill = sex)) +
  geom_bar(position = "stack") + ## don't need "stack" because it's default
  scale_fill_viridis_d()
```

```{r}
penguins |> na.omit() # gets rid of any row with NA
penguins_nomiss <- penguins |> filter(!is.na(sex))
ggplot(data = penguins_nomiss, aes(x = species, fill = sex)) +
  geom_bar(position = "dodge") + 
  scale_fill_viridis_d()

```

Exercise 1.

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(stat = "identity", position = "identity") + facet_null() +
  coord_cartesian()
```

Your turn

1\.

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) + geom_histogram()
```

2\.

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = species)) + geom_boxplot()
```

3\.

```{r}
#a
ggplot(data = penguins, aes(x = bill_length_mm)) + geom_freqpoly(colour = "darkred")
ggplot(data = penguins, aes(x = bill_length_mm)) + geom_freqpoly(aes(colour = species))
```

4.
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = species)) + geom_point(aes(colour = species)) +
  geom_smooth()
ggplot(data = penguins, aes(x = bill_length_mm, y = species)) + geom_point() +
  geom_smooth(aes(colour = species))
```

6\.

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~ species)
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~ island)
```
